apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      containers:
        - name: spark-master
          image: bitnami/spark:latest
          ports:
            - containerPort: 7077
            - containerPort: 8080
          command:
            - /opt/bitnami/spark/bin/spark-class
            - org.apache.spark.deploy.master.Master
          volumeMounts:
            - mountPath: /output
              name: output-volume
      volumes:
        - name: output-volume
          emptyDir: {}