apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      containers:
        - name: spark-worker
          image: jboss17/spark-azure:latest
          env:
            - name: SPARK_MODE
              value: worker
            - name: SPARK_SUBMIT_OPTIONS
              value: >
                --conf spark.jars=/opt/bitnami/spark/jars/hadoop-azure-3.3.2.jar,/opt/bitnami/spark/jars/azure-storage-8.6.6.jar
          ports:
            - containerPort: 8081
          command:
            - /opt/bitnami/spark/bin/spark-class
            - org.apache.spark.deploy.worker.Worker
            - spark://spark-master-service:7077

