apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      containers:
        - name: spark-master
          image: jboss17/spark-azure:latest
          env:
            - name: SPARK_MODE
              value: master
            - name: SPARK_SUBMIT_OPTIONS
              value: >
                --conf spark.jars=/opt/bitnami/spark/jars/hadoop-azure-3.3.2.jar,/opt/bitnami/spark/jars/azure-storage-8.6.6.jar
          ports:
            - containerPort: 7077
            - containerPort: 8080
          command:
            - /opt/bitnami/spark/bin/spark-class
            - org.apache.spark.deploy.master.Master
          volumeMounts:
            - mountPath: /output
              name: output-volume
      volumes:
        - name: output-volume
          emptyDir: {}