apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
spec:
  selector:
    app: spark
    role: master
  ports:
    - name: spark-master
      protocol: TCP
      port: 7077
      targetPort: 7077
    - name: spark-ui
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
